CREATE TABLE SECTION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    company VARCHAR(255),
    dates VARCHAR(255),
    description TEXT,
    responsabilities TEXT,
    technologies TEXT
);

CREATE TABLE RESPONSABILITY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_section BIGINT,
    text TEXT,
    FOREIGN KEY (id_section) REFERENCES SECTION(id)
);

CREATE TABLE TECHNOLOGY (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    id_section BIGINT,
    text TEXT,
    FOREIGN KEY (id_section) REFERENCES SECTION(id)
);

CREATE TABLE SKILL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(255),
    score VARCHAR(10)
);